{{- if and .Values.secret.tls.enabled (not (lookup "v1" "Secret" .Release.Namespace .Values.secret.tls.name)) }}
{{- $crt := .Values.secret.tls.cert | default "" -}}
{{- $key := .Values.secret.tls.key | default "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.tls.name }}
  namespace: {{ .Release.Namespace | default .Values.namespace }}
type: kubernetes.io/tls
data:
  {{- if and $crt $key }}
  tls.crt: {{ $crt | b64enc }}
  tls.key: {{ $key | b64enc }}
  {{- else }}
  {{- fail (printf "❌ Missing TLS files: %s or %s not found in chart directory" .Values.secret.tls.cert .Values.secret.tls.key) }}
  {{- end }}
{{- end }}
