{
 "title": "eDTR Dashboard",
 "tags": [ "eDTR" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "HTTP Requests by Status",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records Processed Total (Attendance)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(attendance_records_processed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU Total (seconds)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Resident Memory (bytes)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(request_duration_seconds_sum[1m]) \n/\nrate(request_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records Processed Total (Employees)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(user_records_processed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Virtual Memory (bytes)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Python GC Object Uncollectable Total",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(python_gc_objects_uncollectable_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch Requests Total (Employees)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(user_fetch_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Python GC Objects Collected Total",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fetch Errors Total (Employees)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(user_fetch_errors_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration (handler-specific latency)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(request_duration_seconds_sum{handler=\"/metrics\"}[1m])\n/\nrate(request_duration_seconds_count{handler=\"/metrics\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}